name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: hello_world
      run: echo "Hello world"
    - name: make
      run: pwd && cd ./tests && make fclean && make test
